#!/bin/bash

# paru and system setup
sudo pacman -S --needed --noconfirm base-devel git
git clone https://aur.archlinux.org/paru-bin.git
cd paru-bin && makepkg -si --noconfirm && cd .. && rm -rf paru-bin

# Raw GNOME install
sudo pacman -S --noconfirm adw-gtk3 gnome-shell nautilus gnome-control-center gdm networkmanager gparted flatpak steam-devices
sudo systemctl enable gdm NetworkManager

# Bibata cursors
paru -S --noconfirm bibata-cursor-theme-bin

# Flatpak/flathub preinstalls
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
flatpak install -y flathub org.gnome.clocks org.gnome.Decibels org.gnome.Snapshot org.gnome.Calculator com.protonvpn.www io.github.kolunmi.Bazaar io.missioncenter.MissionCenter org.gnome.TextEditor com.mattjakeman.ExtensionManager org.gnome.FileRoller org.altlinux.Tuner io.gitlab.adhami3310.Impression org.chromium.Chromium com.raggesilver.BlackBox com.github.tchx84.Flatseal com.vixalien.sticky org.gnome.Showtime it.mijorus.smile org.gnome.Papers org.gnome.Loupe com.github.finefindus.eyedropper com.valvesoftware.Steam

# Theming and GNOME settings sorta stuff
gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Classic'
gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark'
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
gsettings set org.gnome.desktop.wm.preferences button-layout ":minimize,maximize,close"

# Wallpaper application
sudo mkdir -p /usr/share/backgrounds/bubblegum/
sudo curl -L https://raw.githubusercontent.com/caela-uk/os/main/backgrounds/bubblegum/default.png -o /usr/share/backgrounds/bubblegum/default.png
WP_PATH="file:///usr/share/backgrounds/bubblegum/default.png"
gsettings set org.gnome.desktop.background picture-uri "$WP_PATH"
gsettings set org.gnome.desktop.background picture-uri-dark "$WP_PATH"
gsettings set org.gnome.desktop.screensaver picture-uri "$WP_PATH"

# Flatpak theming
flatpak override --user --filesystem=$HOME/.icons:ro --filesystem=$HOME/.themes:ro